import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header.jsx";
import { LanguageProvider } from "./provider/languageProvider";
import { LoadingProvider } from "./provider/LoadingProvider";
import localFont from "next/font/local";
import Footer from "./components/Footer.jsx";
import Image from "next/image";

import whatsapp from "@/public/icons/home/whatsapp_green.svg";
// ایمپورت فونت محلی Yekan Bakh
const yekanBakh = localFont({
  src: "../public/fonts/myfont.ttf",
  variable: "--font-yekan", // برای استفاده در Tailwind
  display: "swap",
});

// فونت‌های گوگل
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="af">
      
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${yekanBakh.variable} font-yekan antialiased min-h-screen flex flex-col`}
      >
        <LanguageProvider>
          <LoadingProvider>
            
          <Header />
          <main className="grow">{children}</main>
           <Image
            src={whatsapp}
            alt="whatsapp"
            className="fixed z-30 w-12 h-12 cursor-pointer bottom-3 right-3 sm:w-14 sm:h-14 md:w-16 md:h-16"
          />
          <Footer />
          </LoadingProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
