import './globals.css';
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import ClientLayout from './components/ClientLayout';

// فونت‌ها
const yekanBakh = localFont({
  src: "../public/fonts/myfont.ttf",
  variable: "--font-yekan",
  display: "swap",
});
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// metadata فقط در Server Layout
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html >
      <body className={`${geistSans.variable} ${geistMono.variable} ${yekanBakh.variable} font-yekan antialiased min-h-screen flex flex-col`}>
        <ClientLayout>{children}</ClientLayout> {/* Client Component */}
      </body>
    </html>
  );
}
