import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header.jsx";
import { LanguageProvider } from "./provider/languageProvider";
import localFont from "next/font/local";
import Footer from "./components/footer/Footer.jsx";
import { SpeedInsights } from "@vercel/speed-insights/next"
// ایمپورت فونت محلی Yekan Bakh
const yekanBakh = localFont({
  src: "../public/fonts/myfont.ttf",
  variable: "--font-yekan", // برای استفاده در Tailwind
  display: "swap",
});

// فونت‌های گوگل
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="af">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${yekanBakh.variable} font-yekan antialiased min-h-screen flex flex-col`}
      >
        <LanguageProvider>
          <Header />
          <main className="grow">{children}</main>
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
