import './globals.css';
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import ClientLayout from './components/ClientLayout';
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider,hasLocale } from "next-intl";

// فونت‌ها
const yekanBakh = localFont({
  src: "../../public/fonts/myfont.ttf",
  variable: "--font-yekan",
  display: "swap",
});
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// metadata فقط در Server Layout
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children,params }) {

  const {locale} =await params;
 
  if (!hasLocale(routing.locales, locale)) {
 
    notFound();
  }
   const dir = locale === "fa" || locale === "ps" ? "ltr" : "rtl";



  return (
    <html lang={locale} dir={dir}>
      <body className={`${geistSans.variable} ${geistMono.variable} ${yekanBakh.variable} font-yekan antialiased min-h-screen flex flex-col`}>
         <NextIntlClientProvider locale={locale}>

        <ClientLayout>{children}</ClientLayout> {/* Client Component */}
         </NextIntlClientProvider>
      </body>
    </html>
  );
}
